language: ruby
rvm: 2.5
addons:
  apt:
    packages:
    - asciidoc
    - libxml2-utils
    - xsltproc
    - docbook-xsl
    - ca-certificates
before_script:
  - wget https://apt.puppetlabs.com/puppet6-release-xenial.deb
  - sudo dpkg -i puppet6-release-xenial.deb
  - sudo apt-get update
  - sudo apt-get install puppet-agent
  - sudo /opt/puppetlabs/puppet/bin/gem install puppet-strings
script:
  - source /etc/profile.d/puppet-agent.sh
  - bundle exec rake rubocop
  #
  # Run rspec tests on migrations
  #
  - bundle exec rake spec
  #
  # Test basic installer configuration works
  #
  - INSTDIR=$(mktemp -d)
  - bundle exec rake build install PREFIX=$INSTDIR
  - bundle exec $INSTDIR/sbin/foreman-installer --help --scenario foreman
  - bundle exec $INSTDIR/sbin/foreman-installer --help --scenario foreman-proxy-content
  - bundle exec $INSTDIR/sbin/foreman-installer --help --scenario katello
  - bundle exec $INSTDIR/sbin/foreman-proxy-certs-generate --help
  - bundle exec $INSTDIR/sbin/foreman-proxy-certs-generate --help |grep -q certs-update-server
  #
  # Run rspec tests again for Puppet version support in modules.
  # This requires all modules to be built.
  #
  - bundle exec rake spec
  #
  # Test separate build/installation steps with different prefixes
  # No references to INSTDIR should be present when built with PREFIX=/
  #
  - bundle exec rake clean build PREFIX=/ SYSCONFDIR=/etc
  - INSTDIR=$(mktemp -d)
  - bundle exec rake install PREFIX=$INSTDIR
  - "! find $INSTDIR -type f | xargs grep $INSTDIR"
  - "! find $INSTDIR -type l -printf '%P: ' -exec readlink {} \\; | grep $INSTDIR"
