---
mongodb::globals::server_package_name: 'rh-mongodb34-syspaths'
mongodb::client::package_name: 'rh-mongodb34-mongodb'
mongodb::globals::service_name: 'rh-mongodb34-mongod'
mongodb::server::config: '/etc/opt/rh/rh-mongodb34/mongod.conf'
mongodb::server::dbpath: '/var/lib/mongodb'
mongodb::server::syslog: true
mongodb::server::logpath: false
mongodb::server::config_template: 'mongodb/mongodb.conf.2.6.erb'
mongodb::server::manage_pidfile: false
mongodb::server::pidfilepath: '/var/opt/rh/rh-mongodb34/run/mongodb/mongod.pid'

postgresql::globals::version: '10'
postgresql::globals::client_package_name: rh-postgresql10-postgresql-syspaths
postgresql::globals::server_package_name: rh-postgresql10-postgresql-server-syspaths
postgresql::globals::contrib_package_name: rh-postgresql10-postgresql-contrib-syspaths
postgresql::globals::service_name: postgresql
postgresql::globals::datadir: /var/opt/rh/rh-postgresql10/lib/pgsql/data
postgresql::globals::confdir: /var/opt/rh/rh-postgresql10/lib/pgsql/data
postgresql::globals::bindir: /usr/bin
