foreman_proxy::plugin::pulp::pulpcore_enabled: true
foreman_proxy::plugin::pulp::pulpcore_mirror: false
foreman_proxy::plugin::pulp::pulpnode_enabled: false
foreman_proxy::plugin::pulp::enabled: true
